school/classroom/urls.py
from django.urls import path
from . import views

app_name = "classroom"

urlpatterns = [
    path('', views.HomeView.as_view(), name='classroom'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('teacher_form/', views.TeacherView.as_view(), name='teacher'),
    path('teacher_list/', views.TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>', views.TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher_update/<int:pk>', views.TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_delete/<int:pk>', views.TeacherDeleteView.as_view(), name='teacher_delete'),
]

school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name} teaches {self.subject}'

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.forms import ContactForm
from classroom.models import Teacher
# Create your views here.

# Below is the function based view
# def classroom_view(request):
#     return render(request, 'classroom/home.html')

class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ThanksView(TemplateView):
    template_name = 'classroom/thanks.html'


class TeacherView(CreateView):
    model = Teacher
    fields = '__all__'
    success_url = reverse_lazy('classroom:teacher_list')


class TeacherListView(ListView):
    model = Teacher
    queryset = Teacher.objects.order_by('first_name')
    # template : model_list.html
    context_object_name = "teacher_list"


class TeacherDetailView(DetailView):
    model = Teacher
    # template : model_detail.html


class TeacherUpdateView(UpdateView):
    # Shares model_list.html (shares same view with creation)
    model = Teacher
    # fields = ['last_name']
    fields = '__all__'
    success_url = reverse_lazy('classroom:teacher_list')


class TeacherDeleteView(DeleteView):
    # default template view : model_confirm_delete.html
    model = Teacher
    success_url = reverse_lazy('classroom:teacher_list')


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # Note : this is a URL and not a html page redirection
    # success_url = '/classroom/thanks'
    success_url = reverse_lazy('classroom:thanks')

    # What to do with the form
    # form is the connection to the form used in the contact.html file.
    # When a valid form is ported
    def form_valid(self, form):
        #form.save()
        print(form.cleaned_data)
        return super().form_valid(form)

school/classroom/templates/classroom/contact.html
{% extends 'index.html' %}

{% load static %}

{% block content %}

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    {{form.errors}}
    <input type="submit" value="Submit">
</form>

{% endblock content %}

school/classroom/templates/classroom/home.html
{% extends 'index.html' %}

{% load static %}

{% block content %}

<h2>Welcome to Home</h2>

<div class="container">
<ul>
    <a href="{% url 'classroom:thanks' %}">Thank you page</a>
</ul>
<ul>
    <a href="{% url 'classroom:contact' %}">Contact us</a>
</ul>
<ul>
    <a href="{% url 'classroom:teacher' %}">Teacher Form</a>
</ul>
<ul>
    <a href="{% url 'classroom:teacher_list' %}">Teacher List</a>
</ul>
</div>

{% endblock content %}

school/classroom/templates/classroom/teacher_confirm_delete.html
{% extends 'index.html' %}


{% block content %}

<h2>Are you sure you want to delete {{teacher.first_name}} ?</h2>

<form action="" method="POST">
    {% csrf_token %}

    <input type="submit" value="Confirm Delete">
</form>

{% endblock content %}

school/classroom/templates/classroom/teacher_detail.html
{% extends 'index.html' %}

{% load static %}

{% block content %}
    {{teacher}}
{% endblock content %}

school/classroom/templates/classroom/teacher_form.html
{% extends 'index.html' %}

{% load static %}

{% block content %}

<div class="container">
    <form action="" method="POST">
    {% csrf_token %}
        {{form.as_p}}
        {{form.errors}}
    <input type="submit">
</form>
</div>

{% endblock content %}

school/classroom/templates/classroom/teacher_list.html
{% extends 'index.html' %}
{% load static %}

{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {% for teacher in teacher_list %}

        <a href='/classroom/teacher_detail/{{teacher.id}}'><li>{{teacher.first_name}} {{teacher.last_name}} teaches {{teacher.subject}}.....</a>
            <li><a href="/classroom/teacher_update/{{teacher.id}}">Update</a></li>
            <li><a href="/classroom/teacher_delete/{{teacher.id}}">Delete</a></li>

        </li>
        {% endfor %}
    </form>
</div>

{% endblock content %}

school/classroom/templates/classroom/thanks.html
{% extends 'index.html' %}

{% block content %}

<h1>Thank you so much!</h1>

{% endblock content %}

school/templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<!-- NAVBAR -->

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">School of Life</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Classroom</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Teachers</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled">Subjects</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

{% block content %}


{% endblock content %}

</body>
</html>