shadow/config/urls.py
from django.urls import path
from config.views import *

app_name = "config"

urlpatterns = [
    path("", ConfigView.as_view(), name="config"),
    path("step_list/", StepList.as_view(), name="step_list"),
    path("step_details/<int:pk>", StepDetails.as_view(), name="step_details"),
    path('download/', StepsDownloadView.as_view(), name="steps_download"),
]

shadow/shadow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.shortcuts import render
# In case we want to redirect the user to catalog page by default, include
# the below line
# path('', RedirectView.as_view(url='catalog/'))

urlpatterns = [
    path("", lambda request: render(request, "index.html"), name="index"),
    # path('', RedirectView.as_view(url='catalog/')),
    path("admin/", admin.site.urls),
    path("testcase/", include("testcase.urls")),
    path("config/", include("config.urls"))
]

shadow/testcase/urls.py
app_name = "testcase"

urlpatterns = []

shadow/config/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.

RAID_TYPES = (
    ("R0", "RAID0"),
    ("R1", "RAID1"),
    ("R5", "RAID5"),
    ("R6", "RAID6"),
    ("R10", "RAID10"),
    ("R50", "RAID50"),
    ("R60", "RAID60"),
    ("JBODs", "JBODs"),
)

STRIPE_SIZE = (
    (256, 256),
    (1024, 1024)
)

NUM_DRIVES = [(i, str(i)) for i in range(0, 240)]

class Configuration(models.Model):
    raid_type = models.CharField(max_length=6, choices=RAID_TYPES, null=False)
    stripe_size = models.IntegerField(choices=STRIPE_SIZE)
    num_drives = models.IntegerField(choices=NUM_DRIVES, validators=(MinValueValidator(1), MaxValueValidator(240)))

    def __str__(self) -> str:
        return f'Create {self.raid_type} with {self.num_drives}'

shadow/testcase/models.py
from django.db import models

# Create your models here.

shadow/config/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from config.models import *
from django.views.generic import CreateView, UpdateView, DetailView, ListView, DeleteView
import json
from django.http import HttpResponse
# Create your views here.

class ConfigView(CreateView):
    model = Configuration
    fields = '__all__'
    success_url = reverse_lazy('config:step_list')


class StepList(ListView):
    model = Configuration
    queryset = Configuration.objects.order_by('id')
    context_object_name = 'step_list'


class StepDetails(DetailView):
    model = Configuration


class StepsDownloadView(ListView):
    model = Configuration

    # def render_to_response(self, context, **response_kwargs):
    def get(self, request, *args, **kwargs):
        # Get the list of submitted steps
        submitted_steps = list(self.get_queryset().values())

        # Convert the list to JSON
        json_data = json.dumps(submitted_steps, indent=4)

        # Create the HTTP response with the JSON data
        response = HttpResponse(json_data, content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="submitted_steps.json"'

        return response

shadow/testcase/views.py
from django.shortcuts import render

# Create your views here.

shadow/config/templates/config/configuration_detail.html
{% extends 'index.html' %}

{% block content %}

<div class="container">
    <h3>Steps detail</h3>
    <hr>
    {{configuration}}
</div>

{% endblock content %}

shadow/config/templates/config/configuration_form.html
{% extends 'index.html' %}

{% block content %}

<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        {{form.as_p}}
        {{form.errors}}
        <input type="submit" value="Submit">
    </form>
</div>

{% endblock content %}

shadow/config/templates/config/configuration_list.html
{% extends 'index.html' %}

{% block content %}

<div class="container">
    <h3>Steps submitted so far</h3>
    <hr>
    <ul>
    {% for step in step_list %}
        <li><a href="/config/step_details/{{step.pk}}">{{step}}</a></li>
    {% endfor %}
    </ul>
    <hr>
    <form action="{% url 'config:steps_download' %}" method="GET">
        {% csrf_token %}
        <input type="submit" value="Download JSON">
    </form>
</div>

{% endblock content %}

shadow/templates/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
    <title>Welcome to Project Shadow</title>
</head>
<body>

    <!--NAVBAR-->
    <nav class="navbar navbar-expand-lg bg-body-tertiary navbar bg-dark border-bottom border-bottom-dark" data-bs-theme="dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Project Shadow</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
              <a class="nav-link" href="#">Features</a>
              <a class="nav-link" href="#">Pricing</a>
              <a class="nav-link disabled">Disabled</a>
            </div>
          </div>
        </div>
      </nav>
      
      <br>
      <br>
      <!--BLOCK CONTENT-->
      {% block content %}
      

      {% endblock content %}

</body>
</html>