my_site/cars/urls.py
from django.urls import path
from . import views

app_name = "cars"

urlpatterns = [
    path('add/', views.add_view, name="add"),
    path('list/', views.list_view, name="list"),
    path('delete/', views.delete_view, name="delete"),
]

my_site/my_site/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("admin/", admin.site.urls),
    # path('wing/', include('wing_man.urls')),
    path('shadow/', include('shadow.urls')),
    path('cars/', include('cars.urls')),
    path('carrental/', include('carrental.urls')),
]

handler404 = 'my_site.views.custom_not_found_view'

my_site/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>
    <h1>Hello, Nebula!</h1>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'cars:add' %}">Add</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:list' %}">List</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'cars:delete' %}">Delete</a>
              </li>

            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
      </nav>

    {% block content %}
    
    {% endblock content %}

    <img src="{% static 'shadow/nebula.png' %}" alt="Nebula" height='100px' width='100px'>

</body>
</html>

my_site/templates/error_view.html
{% extends 'base.html' %}

{% block content %}
    <h1>Error 404 custom</h1>

{% endblock content %}